name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run format
      run: |
        cargo fmt --all
        git config --global user.name "gracetveit"
        git config --global user.email "grace.tveit@gmail.com"

        git add -A
        git commit -m "formatting"
        git push
